--- 
workflows: 
  test-application: 
    name: "Test workflow"
    scripts: 
      - 
        name: Started
        script: "echo \"It's working!\""
      - 
        name: Building
        script: "xcodebuild build -workspace \"project.xcworkspace\" -scheme \"project\" CODE_SIGN_INDENTITY=\"\" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO"
